type ItemContent {
  body: String
  title: String
  metaTitle: String
  metaDescription: String
  json: String
}

type Item {
  url: String! @unique
  createdBy: String!
  createdAt: Long!
  content: ItemContent
}

type List {
  name: String!
  createdBy: String!
  createdAt: Long!
}

type ListItem {
  item: Item!
  list: List!
  createdBy: String!
  createdAt: Long!
}

type TextSelection {
  text: String!
  item: Item
  createdBy: String!
  createdAt: Long!
}

type TextSelectionCount {
  item: Item!
  count: Int!
  createdBy: String!
}

type UserMetadata {
  emailIngestAddress: String
  phoneNumber: String
  userId: String!
}

type SmsVerifierPinSet {
  expiresAt: Long!
  number: Int!
  pin: String!
  userId: String!
}

type ReceivedEmailBlobsV1 {
  json: String
}

type Query {
  allItems: [Item!]

  allItemsReverseChrono: [Item!]
  @resolver(name: "all_Items_reverse_chrono", paginated: true)

  allLists: [List!]

  allListItems: [ListItem!]

  findListItemsByList(id: String!): [ListItem]
  @resolver(name: "list_items_for_list", paginated: true)

  allTextSelections: [TextSelection!]

  returnUserId(userId: String!): String @resolver(name: "return_user_id")

  clipsByUser(userId: String!): [TextSelection!]
  @resolver(name: "clips_by_user", paginated: true)

  listsByUser(userId: String!): [List!]
  @resolver(name: "lists_by_user", paginated: true)

  itemsByUser(userId: String!): [Item!]
  @resolver(name: "items_by_user", paginated: true)

  itemsByUserReverse(userId: String!): [Item!]
  @resolver(name: "items_by_user_reverse", paginated: true)

  clipsByItemId(itemId: String!): [TextSelection!]
  @resolver(name: "clips_by_item_id", paginated: true)

  mostPopularItemsByUser(userId: String!): [Item!]
  @resolver(name: "most_clipped_items_by_user", paginated: true)

  userMetadataForUser(userId: String!): UserMetadata
  @resolver(name: "userMetadataForUser")
}
