type Item {
  url: String! @unique
}

type List {
  name: String!
}

type ListItem {
  item: Item!
  list: List!
}

type TextSelection {
  text: String!
  item: Item!
}

type Query {
  allItems: [Item!]
  allItemsReverseChrono: [Item!]
    @resolver(name: "all_Items_reverse_chrono", paginated: true)
  allLists: [List!]
  allListItems: [ListItem!]
  findListItemsByList(id: String!): [ListItem]
    @resolver(name: "list_items_for_list", paginated: true)
  allTextSelections: [TextSelection!]
}
